<a href="https://colab.research.google.com/github/pooyalHsu/20230205python/blob/main/20230219_%E7%AD%86%E8%A8%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 簡單程式碼測試
* https://python.microbit.org/v/3
* % 代表餘數，使用時，需要知道我的可循環的最大值，讓程式在跑的時候不會超過最大值，而是會在固定值中循環

嘗試執行底下程式，按按鈕A乾ㄔ

```python
# Imports go at the top
from microbit import *

display.clear()

x = 0
y = 0
display.set_pixel(x,y,9)

while True:
    if button_a.was_pressed():
        x = x + 1
        display.clear()
        display.set_pixel(x%5,y,9)
```

# 複習requests的使用

從政府資料開放平台抓資料: https://data.gov.tw/

## 練習

### 抓取年度國內主要金融指標下來做分析

https://apiservice.mol.gov.tw/OdService/download/A17000000J-030244-dpp

In [9]:
#載入我要用的模組
import requests

In [6]:
#輸入我要抓取的網址
url = "https://apiservice.mol.gov.tw/OdService/download/A17000000J-030244-dpp"

In [21]:
#讓資料轉換成json
data = requests.get(url).json()

In [23]:
#檢視data裡面有幾筆資料
type(data)

list

In [24]:
#此清單中有幾筆資料
len(data)

29

#### 方法一，列出每年度貨幣供給額其底年增率

In [ ]:
for i in data:
  print(i['年度'], "==>", i['貨幣供給額期底年增率-M2'])

#### 方法二

In [ ]:
for i in range(len(data)):
  print(i)


In [32]:
for i in range(len(data)):
  print(data[i]['年度'], "==>", data[i]['貨幣供給額期底年增率-M2'])

1994 ==> 15.07
1995 ==> 9.42
1996 ==> 9.13
1997 ==> 8.02
1998 ==> 8.56
1999 ==> 8.29
2000 ==> 6.50
2001 ==> 4.31
2002 ==> 2.53
2003 ==> 5.68
2004 ==> 7.19
2005 ==> 6.63
2006 ==> 5.15
2007 ==> 0.84
2008 ==> 7.21
2009 ==> 5.78
2010 ==> 5.44
2011 ==> 4.84
2012 ==> 3.46
2013 ==> 5.79
2014 ==> 6.13
2015 ==> 5.80
2016 ==> 3.55
2017 ==> 3.56
2018 ==> 2.65
2019 ==> 4.52
2020 ==> 9.36
2021 ==> 7.35
2022 ==> 6.74


## 資料分資料分析基礎
* numpy ==> 科學運算基礎套件
* matplotlib ==> 繪圖機處套件
* pandas ==> 資料分析基礎套件

### 套件載入的慣用法
```python
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
````

### NumPy
* NumPy ==> **Num**merical **Py**thon
* ndarray ==> N-Dimensional Arrays
* ufunc (通用函式) ==> Universal Functions

In [33]:
import numpy as np

#### 原生的python的容器型別的限制

無法簡單的做到科學(向量)運算!

In [34]:
x = [1,2,3]
y = [4,5,6]

In [36]:
x + y

[1, 2, 3, 4, 5, 6]

#### 使用numpy的ndarray來解決科學運算的問題

In [37]:
#讓x1成為x的陣列
x1 = np.array(x)
y1 = np.array(y)

In [38]:
type(x1)

numpy.ndarray

In [41]:
x1

array([1, 2, 3])

In [39]:
x1 + y1

array([5, 7, 9])

### ufunk

#### 原生的pthon的數學運算

In [46]:
import math

In [47]:
math.pi

3.141592653589793

In [48]:
math.sin(math.pi/2)

1.0

#### 比較一下numpy的使用

In [50]:
np.pi

3.141592653589793

In [51]:
np.sin(np.pi/2)

1.0

In [52]:
np.sin(x)

array([0.84147098, 0.90929743, 0.14112001])